### ISSUE TITLE
`mockNuxtImport` failing to mock Nuxt auto imports

### ISSUE THREAD

**Issue by yoji-kojio** [danielroe/nuxt-vitest#95] opened 2023-03-15 16:15 UTC
Hey guys, today I upgraded `vitest` and `nuxt-vitest` to version [0.29.2](https://github.com/vitest-dev/vitest/releases/tag/v0.29.2) and [0.6.8](https://github.com/danielroe/nuxt-vitest/releases/tag/0.6.8), respectively.

I upgraded `nuxt-vitest` because I upgraded `vitest` and installed `c8` for test coverage and I started getting the following error message on test runs:
```
Error: Cannot find module 'vitest-environment-nuxt/module'
```

And after the `nuxt-vitest` upgrade, I started getting the following error:
```
Error: Cannot find import "useI18n" to mock
```

And this happens when I try to mock `useI18n` (from `@nuxtjs/i18n`), which exists globally in my application:
```javascript
import { mockNuxtImport } from 'nuxt-vitest/utils'

mockNuxtImport('useI18n', () => {
  return () => {
    return {
      t: vi.fn()
    }
  }
})
```

Before all these upgrades, the mock was working properly.
Anyone else with a similar problem?

*EXTRA INFORMATION*
On the other hand...
My original approach to mock i18n started to work (didn't work before):
```javascript
import { useI18n } from 'vue-i18n'
import { vi } from 'vitest'

vi.mock('vue-i18n')

useI18n.mockReturnValue({
  t: (tKey) => tKey
})
```
And I using this approach for now. And why it didn't work before is a mystery...

**Comment by yoji-kojio** [comment] 2023-03-15 16:18
On the other hand...
My original approach to mock `i18n` started to work (didn't work before):
```javascript
import { useI18n } from 'vue-i18n'
import { vi } from 'vitest'

vi.mock('vue-i18n')

useI18n.mockReturnValue({
  t: (tKey) => tKey
})
```

And I using this approach for now. And why it didn't work before is a mystery...

**Comment by matheusm** [comment] 2023-03-15 16:21
I had the same issue here

**Comment by ghazialhouwari** [comment] 2023-03-16 09:16
@yoji-kojio are you using `nuxt-i18n`?

**Comment by yoji-kojio** [comment] 2023-03-16 16:52
> @yoji-kojio are you using `nuxt-i18n`?

yes, I'm using the nuxt 3 compatible version: https://v8.i18n.nuxtjs.org/
`"@nuxtjs/i18n": "^8.0.0-beta.9"`

**Comment by ghazialhouwari** [comment] 2023-03-16 17:28
@yoji-kojio This issue is duplicate of https://github.com/danielroe/nuxt-vitest/issues/88
I already opened a pull request and referenced it there.

**Closed** 2023-03-16 21:44 UTC
